### ISSUE TITLE
POST throws {"errors":[{"message":"Could not authenticate you","code":32}]}

### ISSUE THREAD

**Issue by lakshmananvelusamy** [J7mbo/twitter-api-php#145]
Hi ,
The following post code is throwing "could not authenticate you" error where as the get works with the same set of tokens and credentials.

Code:
-------
<?php
ini_set('display_errors', true	);
require_once('TwitterAPIExchange.php');

/** Set access tokens here - see: https://dev.twitter.com/apps/ **/
$settings = array(
    'oauth_access_token' => "--access_token---",
    'oauth_access_token_secret' => "---token_secret---",
    'consumer_key' => "---consumer_key---",
    'consumer_secret' => "---consumer_secret---"
);

/** URL for REST request, see: https://dev.twitter.com/docs/api/1.1/ **/
$url = 'https://api.twitter.com/1.1/statuses/update.json';
$requestMethod = 'POST';

/** POST fields required by the URL above. See relevant docs as above **/
$postfields = array(
			 'in_reply_to_status_id' => 629175335863627776,
            'status' => 'TEST'
);

/** Perform a POST request and echo the response **/
$twitter = new TwitterAPIExchange($settings);
echo $twitter->buildOauth($url, $requestMethod)
             ->setPostfields($postfields)
             ->performRequest();

----------

Thanks,
Lakshmanan!

**Comment by lakshmananvelusamy** [comment]
get code:
-----------
$settings = array(
    'oauth_access_token' => "--same_access_token---",
    'oauth_access_token_secret' => "---same_token_secret---",
    'consumer_key' => "---same_consumer_key---",
    'consumer_secret' => "---same_consumer_secret---"
);
----------

I have also regenerated all the tokens. Didn't help!!

**Comment by J7mbo** [comment]
Okay, let's start with **GET** first. Looks like you're trying to get the data of [this tweet](https://twitter.com/book_tribe/status/628499119364014080)? I added a [test which proves this works](https://github.com/J7mbo/twitter-api-php/blob/bug-145/test/TwitterAPIExchangeTest.php#L308-L320).

I know you say that you have regenerated the tokens, but on that front I recommend you try again. If you look at the code above and also the [travis CI tool](https://travis-ci.org/J7mbo/twitter-api-php/builds/74440687) actually running that code, you'll see it passes.

---

Now onto the **POST** part.. I *think* this is because you're trying to reply to a *protected tweet*. You can go directly to a tweet by going to twitter.com/anyusernamehereitdoesntmatter/status/tweet_id. That redirects you to the correct status. However, try visiting: http://twitter.com/j7mbo/status/629175335863627776 and then check the url when it's loaded. It contains `?protected_redirect=true`. Is it a protected account you're trying to talk with?

**Comment by lakshmananvelusamy** [comment]
I removed protected_tweet setting and made a new tweet (https://twitter.com/lakshmanan_v/status/629358657864626176) which isn't protected. Still getting the same error.

**Comment by lakshmananvelusamy** [comment]
Posting a new tweet works. 

$postfields = array(
//			 'in_reply_to_status_id' => 629358657864626176,
            'status' => 'TEST'
);

But if i uncomment in_reply_to_status_id param it stops working!

**Comment by glenscott** [comment]
Could be an issue with the parameter being an integer rather than a string?

**Comment by lakshmananvelusamy** [comment]
U got it. Thats the issue. Reply to tweet is working fine now :+1: 

Thanks!!

**Comment by J7mbo** [comment]
Hmm, trying to decide if we should automatically convert all integers to strings with a check similar to the boolean one. Need to do some research into the other methods and see what they take.

**Comment by glenscott** [comment]
@J7mbo In my opinion, yes, non-strings should be converted to strings.  This is a PHP issue rather than an API issue, so changing to strings will have no effect on other API methods.
