### ISSUE TITLE
sometime timeout when call media upload

### ISSUE THREAD

**Issue by nvcken** [J7mbo/twitter-api-php#170]
got error
```
Fatal error: Uncaught exception 'Exception' with message 'Operation timed out after 10000 milliseconds with 0 bytes received' in /lib/TwitterAPIExchange.php:305
Stack trace:
#0 index.php(41): TwitterAPIExchange->performRequest()

```

**Comment by J7mbo** [comment]
This is likely because you're behind some kind of shared hosting that's blocking the calls? It shouldn't take 10 seconds to make a request.

Regardless, that's a cURL error converted to an exception. If you look at [performRequest()](https://github.com/J7mbo/twitter-api-php/blob/master/TwitterAPIExchange.php#L265) you'll see the second parameter allows you to pass custom cURL parameters through.

With that in mind, you could try increasing the timeout:

    performRequest(true, ['CURLOPT_TIMEOUT', 20]);

> CURLOPT_TIMEOUT	The maximum number of seconds to allow cURL functions to execute

There's also:

> CURLOPT_TIMEOUT_MS The maximum number of milliseconds to allow cURL functions to execute

All the available options are in the [php manual](http://www.php.net/manual/en/function.curl-setopt.php).

You can keep upping the time limit to be able to make a request, but something is being blocked and taking a **long** time that shouldn't be there for you to make a single simple request to twitter. Try pinging twitter from the box to see if you can even talk to them. This doesn't look like an issue on the wrapper's side.

**Comment by nvcken** [comment]
I tried it, thanks for help.
```
performRequest(true, [CURLOPT_TIMEOUT => 20]);
```

**Comment by micper69** [comment]
This
`performRequest(true, [CURLOPT_TIMEOUT => 20]);`

cannot work because options array passed to the method is appended to the library's base options:

```
        $options = array(
            CURLOPT_HTTPHEADER => $header,
            CURLOPT_HEADER => false,
            CURLOPT_URL => $this->url,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_TIMEOUT => 10,
        ) + $curlOptions;
```
