### ISSUE TITLE
chunked media upload

### ISSUE THREAD

**Issue by s-low** [J7mbo/twitter-api-php#197]
Does the library support the chunked upload endpoint for images and videos?

https://dev.twitter.com/rest/reference/post/media/upload

If not is anyone aware of a workaround or imminent PR to support it?

**Comment by J7mbo** [comment]
This is an old post, but I'm looking at the [chunked media upload documentation](https://dev.twitter.com/rest/reference/post/media/upload-init) and it looks pretty standard.

You make a POST request to `https://upload.twitter.com/1.1/media/upload.json` like so:

    https://upload.twitter.com/1.1/media/upload.json?command=INIT&total_bytes=10240&media_type=image/jpeg

Looks like you use the `media` attribute like [here](https://dev.twitter.com/rest/reference/post/media/upload) although I could be wrong.

Also, `curl_file_create()` exists in PHP to help with this.

If you can't get it working, I'm happy to write a test to show it working. Otherwise I'll close this issue (because it's an old one). If you still have a problem with it, feel free to re-open or open a new issue if the library isn't doing what it should be doing.
