### ISSUE TITLE
nothing is printed

### ISSUE THREAD

**Issue by Awamia** [J7mbo/twitter-api-php#21]
I am out of shape. I have not been coding for a few years. I set the setting values with my keys. I put a username of my choice. I commented the post command and tried only the get one. However, nothing is displayed. I am not sure what it's wrong. I set the E_ALL in php.ini to show error but nothing is shown at all. Any ideas? 

here is my code:

<?php
ini_set('display_errors', 1);
require_once('TwitterAPIExchange.php');

/*\* Set access tokens here - see: https://dev.twitter.com/apps/ **/
$settings = array(
    'oauth_access_token' => '79029053####',
    'oauth_access_token_secret' => 'f42ur3s####,
    'consumer_key' => 'fJiOZy9####',
    'consumer_secret' => 'XmLR4###'
);

/*\* URL for REST request, see: https://dev.twitter.com/docs/api/1.1/ **/
$url = 'https://api.twitter.com/1.1/blocks/create.json';
$requestMethod = 'POST';

/*\* POST fields required by the URL above. See relevant docs as above **/
$postfields = array(
    'screen_name' => 'usernameToBlock', 
    'skip_status' => '1'
);

/*\* Perform a POST request and echo the response **/
/*
$twitter = new TwitterAPIExchange($settings);
echo $twitter->buildOauth($url, $requestMethod)
             ->setPostfields($postfields)
             ->performRequest();
*/
/** Perform a GET request and echo the response **/
/** Note: Set the GET field BEFORE calling buildOauth(); **/
$url = 'https://api.twitter.com/1.1/followers/ids.json';
$getfield = '?screen_name=usernamehere';
$requestMethod = 'GET';
$twitter = new TwitterAPIExchange($settings);
echo $twitter->setGetfield($getfield)
             ->buildOauth($url, $requestMethod)
             ->performRequest();

**Comment by eclecticD** [comment]
Hi j7mbo...thanks for the class. works fine for me pretty much all the time . Here's the interesting problem I have. When I try to wrap the call in a class method, i get null returned as other people above. Doesn't seem to be a certificate issue since it works when not wrapped in a class method. Trying to implement this for an application written using the MVC pattern, therefore the need for a class. Here's the very simple code im using to test it. Note ..I did a var_dump to make sure the twitterObj is actually being created ok, and it looks fine. I'm on MAC, dreamhost linux virtual hosting.Any ideas? 

public function tweetMiner()
    {                   
     $getfield='arsenal';
     $requestMethod='GET';
     $url='https://api.twitter.com/1.1/search/tweets.json';  
    
     //get all the info twitter responds with
     $twitterObj = new TwitterAPIExchange($this->settings);
     $response=json_decode( $twitterObj->setGetfield($getfield)->buildOauth($url,$requestMethod)->performRequest() );  

     echo '<pre>';
     var_dump($response);
       }

settings is public in the class and In the class constructor I have this:

public function __construct(){
      require_once 'TwitterAPIExchange.php';
      require_once 'Database.php';

      $this->settings=array(
                      'oauth_access_token'=>"#####",
                      'oauth_access_token_secret'=>"#####",
                      'consumer_key'=>"#####",
                      'consumer_secret'=>"#####"
                      );      
    }
